#DEPLOYMENT POSTGRESQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: juan-namespace
  labels:
    app: postgres-server
spec:
  selector:
    matchLabels:
      app: postgres-server
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-server
    spec:
      containers:
      - image: postgres:11  #docker pull image
        name: postgres-db1
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-db-volume1
        env:
          - name: POSTGRES_PASSWORD #Definición de la variable de entorno
            valueFrom:
              configMapKeyRef:
                name: postgres-configmap #referencia del nombre del configMap
                key: POSTGRES_PASSWORD #hacer referencia a la variable de entorno donde guarda el valor
          - name: POSTGRES_USER #Definición de la variable de entorno
            valueFrom:
              configMapKeyRef:
                name: postgres-configmap #referencia del nombre del configMap
                key: POSTGRES_USER #hacer referencia a la variable de entorno donde guarda el valor
          - name: POSTGRES_DB #Definición de la variable de entorno
            valueFrom:
              configMapKeyRef:
                name: postgres-configmap #referencia del nombre del configMap
                key: POSTGRES_DB #hacer referencia a la variable de entorno donde guarda el valor
      volumes:
      - name: postgres-db-volume1
        persistentVolumeClaim:
           claimName: pvc-juan
---

#CONFIGMAP POSTGRES
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: postgres-configmap 
  namespace: juan-namespace
  labels:
    app: postgres-server
data: # Configuration values can be set as key-value properties
  POSTGRES_PASSWORD: "1234"
  POSTGRES_USER: "juan"
  POSTGRES_DB: "juandb"