#service
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: juan-namespace
  labels:
    app: postgres-server
spec:
  selector:
    app: postgres-server #hacer referencia a la app de algun pod
  ports:  
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8000 #puerto que se desea conectar
      targetPort: 5432 #puerto por defecto de la app
      protocol: TCP #protocolo que se utilizara
  type: LoadBalancer #el tipo de servicio